/**
 * Pre-built workflow examples (recipes) for the Workflow Builder.
 *
 * These presets help users understand how to use the workflow builder
 * by providing real-world examples they can load, explore, and modify.
 */

/**
 * Default settings for a new phase.
 */
export const DEFAULT_PHASE_SETTINGS = {
  depth: 2,
  edgeDirection: "ANY",
  allowedCollections: [],
  edgeFilters: { Label: [], Source: [] },
  setOperation: "Union",
  graphType: "ontologies",
  collapseLeafNodes: true,
  useFocusNodes: true,
  includeInterNodeEdges: true,
  // Filter results to only include nodes from these collections (empty = all)
  returnCollections: [],
};

/**
 * Creates a new empty phase with default settings.
 * @param {number} index - The phase index (0-based).
 * @returns {Object} A new phase object.
 */
export const createEmptyPhase = (index) => ({
  id: `phase-${Date.now()}-${index}`,
  name: "",
  originSource: index === 0 ? "manual" : "previousPhase",
  originNodeIds: [],
  previousPhaseId: null,
  originFilter: "all",
  settings: { ...DEFAULT_PHASE_SETTINGS },
  // Per-node settings overrides (nodeId -> settings object)
  perNodeSettings: {},
  // Whether to show advanced per-node settings UI
  showAdvancedSettings: false,
  result: null,
});

/**
 * Pre-built workflow presets.
 */
export const WORKFLOW_PRESETS = [
  {
    id: "cell-types-in-lung",
    name: "Cell types in the lung",
    description:
      "Returns all cell types that are part of or subclasses of lung-associated cells.",
    category: "Cell Type Discovery",
    phases: [
      {
        id: "preset-lung-cells-phase-1",
        name: "Cell types in lung",
        originSource: "manual",
        originNodeIds: ["UBERON/0002048"], // Lung
        previousPhaseId: null,
        originFilter: "all",
        settings: {
          depth: 9,
          edgeDirection: "INBOUND",
          allowedCollections: ["CL"],
          edgeFilters: { Label: ["PART_OF", "SUB_CLASS_OF"], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: true,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["CL"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
    ],
  },
  {
    id: "epithelial-cells-lung",
    name: "Epithelial cells in the lung",
    description:
      "Intersects the epithelial cell hierarchy with lung anatomy to find shared cell types.",
    category: "Cell Type Discovery",
    phases: [
      {
        id: "preset-epithelial-phase-1",
        name: "Intersect Lung + Epithelium",
        originSource: "manual",
        originNodeIds: ["CL/0000066", "UBERON/0002048"], // Epithelial cell + Lung
        previousPhaseId: null,
        originFilter: "all",
        settings: {
          depth: 9,
          edgeDirection: "INBOUND",
          allowedCollections: ["CL", "UBERON"],
          edgeFilters: { Label: ["PART_OF", "SUB_CLASS_OF"], Source: [] },
          setOperation: "Intersection",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
        },
        // Per-node settings - different depths for each origin node
        perNodeSettings: {
          "CL/0000066": { depth: 9 },
          "UBERON/0002048": { depth: 1 },
        },
        showAdvancedSettings: true,
        result: null,
      },
    ],
  },
  {
    id: "dendritic-marker-genes",
    name: "Marker genes for lung dendritic cells",
    description:
      "First finds dendritic cells in lung via intersection, then expands to their biomarker combinations.",
    category: "Marker Gene Analysis",
    phases: [
      {
        id: "preset-dendritic-phase-1",
        name: "Find dendritic cells in lung",
        originSource: "manual",
        originNodeIds: ["CL/0000451", "UBERON/0002048"], // Dendritic cell + Lung
        previousPhaseId: null,
        originFilter: "all",
        settings: {
          depth: 9,
          edgeDirection: "INBOUND",
          allowedCollections: ["CL", "UBERON"],
          edgeFilters: { Label: ["PART_OF", "SUB_CLASS_OF"], Source: [] },
          setOperation: "Intersection",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
        },
        perNodeSettings: {
          "CL/0000451": { depth: 9 },
          "UBERON/0002048": { depth: 1 },
        },
        showAdvancedSettings: true,
        result: null,
      },
      {
        id: "preset-dendritic-phase-2",
        name: "Expand to marker genes",
        originSource: "previousPhase",
        originNodeIds: [],
        previousPhaseId: "preset-dendritic-phase-1",
        originFilter: "all",
        settings: {
          depth: 2,
          edgeDirection: "ANY",
          allowedCollections: ["BMC", "GS", "UBERON"],
          edgeFilters: { Label: [], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["BMC"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
    ],
  },
  {
    id: "lung-marker-gene-panel",
    name: "Lung cell type marker gene panel",
    description:
      "Returns gene symbols linked to lung cell types via evidence-based relationships.",
    category: "Marker Gene Analysis",
    phases: [
      {
        id: "preset-lung-panel-phase-1",
        name: "Lung cell type markers",
        originSource: "manual",
        originNodeIds: ["UBERON/0002048"], // Lung
        previousPhaseId: null,
        originFilter: "all",
        settings: {
          depth: 2,
          edgeDirection: "ANY",
          allowedCollections: ["CL", "BMC", "GS"],
          edgeFilters: { Label: [], Source: [] },
          setOperation: "Union",
          graphType: "phenotypes",
          collapseLeafNodes: true,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["GS"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
    ],
  },
  {
    id: "cell-type-hierarchy",
    name: "Explore cell type hierarchy",
    description:
      "Traverses subclass relationships to show parent and child cell types. Add your own starting cell type.",
    category: "Ontology Exploration",
    phases: [
      {
        id: "preset-hierarchy-phase-1",
        name: "Cell type hierarchy",
        originSource: "manual",
        originNodeIds: [], // User will fill this in
        previousPhaseId: null,
        originFilter: "all",
        settings: {
          depth: 3,
          edgeDirection: "ANY",
          allowedCollections: ["CL"],
          edgeFilters: { Label: ["SUB_CLASS_OF"], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: true,
          useFocusNodes: true,
          includeInterNodeEdges: true,
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
    ],
  },
  {
    id: "lung-markers-to-diseases",
    name: "Lung marker genes to diseases",
    description:
      "First finds biomarker combinations in the lung, then traces those markers to associated diseases.",
    category: "Disease Analysis",
    phases: [
      {
        id: "preset-lung-disease-phase-1",
        name: "Find lung marker genes",
        originSource: "manual",
        originNodeIds: ["UBERON/0002048"], // Lung
        previousPhaseId: null,
        originFilter: "all",
        settings: {
          depth: 2,
          edgeDirection: "ANY",
          allowedCollections: ["BMC", "CS", "UBERON"],
          edgeFilters: { Label: [], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["BMC"], // Only return marker genes, not anatomy
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
      {
        id: "preset-lung-disease-phase-2",
        name: "Find associated diseases",
        originSource: "previousPhase",
        originNodeIds: [],
        previousPhaseId: "preset-lung-disease-phase-1",
        originFilter: "all",
        settings: {
          depth: 2,
          edgeDirection: "ANY",
          allowedCollections: ["BMC", "GS", "MONDO"],
          edgeFilters: { Label: [], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["MONDO"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
    ],
  },
  {
    id: "disease-cellular-pathogenesis",
    name: "Disease cellular pathogenesis",
    description:
      "Starts from pulmonary hypertension to find associated genes, then identifies the cell types involved. Swap in any disease to explore.",
    category: "Disease Analysis",
    phases: [
      {
        id: "preset-pathogenesis-phase-1",
        name: "Find disease-associated genes",
        originSource: "manual",
        originNodeIds: ["MONDO/0005149"], // Pulmonary hypertension
        previousPhaseId: null,
        originFilter: "all",
        settings: {
          depth: 9,
          edgeDirection: "INBOUND",
          allowedCollections: ["MONDO", "GS"],
          edgeFilters: { Label: ["SUB_CLASS_OF", "GENETIC_BASIS_FOR"], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
      {
        id: "preset-pathogenesis-phase-2",
        name: "Explore cellular contributions",
        originSource: "previousPhase",
        originNodeIds: [],
        previousPhaseId: "preset-pathogenesis-phase-1",
        originFilter: "all",
        settings: {
          depth: 1,
          edgeDirection: "ANY",
          allowedCollections: ["BMC", "CHEBI", "CL", "GS", "PR"],
          edgeFilters: { Label: [], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["CL"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
    ],
  },
  {
    id: "ph-drugs",
    name: "Drugs for pulmonary hypertension",
    description:
      "What drugs are used to treat pulmonary hypertension? Finds molecular entities and bioactive molecules associated with the disease.",
    category: "Disease Analysis",
    phases: [
      {
        id: "preset-ph-drugs-phase-1",
        name: "Find drugs for pulmonary hypertension",
        originSource: "manual",
        originNodeIds: ["MONDO/0005149"], // Pulmonary hypertension
        previousPhaseId: null,
        originFilter: "all",
        settings: {
          depth: 9,
          edgeDirection: "INBOUND",
          allowedCollections: ["MONDO", "CHEBI", "CHEMBL"],
          edgeFilters: { Label: ["SUB_CLASS_OF", "HAS_ROLE"], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["CHEBI", "CHEMBL"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
    ],
  },
  {
    id: "ph-drug-targets",
    name: "Drug targets for PH drugs",
    description:
      "What are the gene/protein targets of pulmonary hypertension drugs? First finds drugs, then traces to their molecular targets.",
    category: "Disease Analysis",
    phases: [
      {
        id: "preset-ph-targets-phase-1",
        name: "Find drugs for pulmonary hypertension",
        originSource: "manual",
        originNodeIds: ["MONDO/0005149"], // Pulmonary hypertension
        previousPhaseId: null,
        originFilter: "all",
        settings: {
          depth: 9,
          edgeDirection: "INBOUND",
          allowedCollections: ["MONDO", "CHEBI", "CHEMBL"],
          edgeFilters: { Label: ["SUB_CLASS_OF", "HAS_ROLE"], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["CHEBI", "CHEMBL"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
      {
        id: "preset-ph-targets-phase-2",
        name: "Find gene/protein targets",
        originSource: "previousPhase",
        originNodeIds: [],
        previousPhaseId: "preset-ph-targets-phase-1",
        originFilter: "all",
        settings: {
          depth: 1,
          edgeDirection: "ANY",
          allowedCollections: ["CHEBI", "CHEMBL", "GS", "PR"],
          edgeFilters: { Label: [], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["GS", "PR"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
    ],
  },
  {
    id: "ph-drug-target-cell-types",
    name: "Cell types expressing PH drug targets",
    description:
      "Which cell types express the gene/protein targets of PH drugs? Chains drugs → targets → cell types in three phases.",
    category: "Disease Analysis",
    phases: [
      {
        id: "preset-ph-cells-phase-1",
        name: "Find drugs for pulmonary hypertension",
        originSource: "manual",
        originNodeIds: ["MONDO/0005149"], // Pulmonary hypertension
        previousPhaseId: null,
        originFilter: "all",
        settings: {
          depth: 9,
          edgeDirection: "INBOUND",
          allowedCollections: ["MONDO", "CHEBI", "CHEMBL"],
          edgeFilters: { Label: ["SUB_CLASS_OF", "HAS_ROLE"], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["CHEBI", "CHEMBL"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
      {
        id: "preset-ph-cells-phase-2",
        name: "Find gene/protein targets",
        originSource: "previousPhase",
        originNodeIds: [],
        previousPhaseId: "preset-ph-cells-phase-1",
        originFilter: "all",
        settings: {
          depth: 1,
          edgeDirection: "ANY",
          allowedCollections: ["CHEBI", "CHEMBL", "GS", "PR"],
          edgeFilters: { Label: [], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["GS", "PR"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
      {
        id: "preset-ph-cells-phase-3",
        name: "Find cell types expressing targets",
        originSource: "previousPhase",
        originNodeIds: [],
        previousPhaseId: "preset-ph-cells-phase-2",
        originFilter: "all",
        settings: {
          depth: 1,
          edgeDirection: "ANY",
          allowedCollections: ["BMC", "CL", "GS", "PR"],
          edgeFilters: { Label: [], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["CL"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
    ],
  },
  {
    id: "ph-full-pipeline",
    name: "PH: drugs → targets → cells → pathogenesis",
    description:
      "Full pipeline: find PH drugs, their gene/protein targets, the cell types expressing them, and the cellular contribution to pathogenesis.",
    category: "Disease Analysis",
    phases: [
      {
        id: "preset-ph-full-phase-1",
        name: "Find drugs for pulmonary hypertension",
        originSource: "manual",
        originNodeIds: ["MONDO/0005149"], // Pulmonary hypertension
        previousPhaseId: null,
        originFilter: "all",
        settings: {
          depth: 9,
          edgeDirection: "INBOUND",
          allowedCollections: ["MONDO", "CHEBI", "CHEMBL"],
          edgeFilters: { Label: ["SUB_CLASS_OF", "HAS_ROLE"], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["CHEBI", "CHEMBL"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
      {
        id: "preset-ph-full-phase-2",
        name: "Find gene/protein targets",
        originSource: "previousPhase",
        originNodeIds: [],
        previousPhaseId: "preset-ph-full-phase-1",
        originFilter: "all",
        settings: {
          depth: 1,
          edgeDirection: "ANY",
          allowedCollections: ["CHEBI", "CHEMBL", "GS", "PR"],
          edgeFilters: { Label: [], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["GS", "PR"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
      {
        id: "preset-ph-full-phase-3",
        name: "Find cell types expressing targets",
        originSource: "previousPhase",
        originNodeIds: [],
        previousPhaseId: "preset-ph-full-phase-2",
        originFilter: "all",
        settings: {
          depth: 1,
          edgeDirection: "ANY",
          allowedCollections: ["BMC", "CL", "GS", "PR"],
          edgeFilters: { Label: [], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["CL"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
      {
        id: "preset-ph-full-phase-4",
        name: "Cellular contribution to pathogenesis",
        originSource: "previousPhase",
        originNodeIds: [],
        previousPhaseId: "preset-ph-full-phase-3",
        originFilter: "all",
        settings: {
          depth: 1,
          edgeDirection: "ANY",
          allowedCollections: ["BMC", "CL", "GS", "MONDO", "PR"],
          edgeFilters: { Label: [], Source: [] },
          setOperation: "Union",
          graphType: "ontologies",
          collapseLeafNodes: false,
          useFocusNodes: true,
          includeInterNodeEdges: true,
          returnCollections: ["MONDO"],
        },
        perNodeSettings: {},
        showAdvancedSettings: false,
        result: null,
      },
    ],
  },
];

/**
 * Categories for organizing presets in the UI.
 */
export const PRESET_CATEGORIES = [
  { id: "Cell Type Discovery", label: "Cell Type Discovery" },
  { id: "Marker Gene Analysis", label: "Marker Gene Analysis" },
  { id: "Ontology Exploration", label: "Ontology Exploration" },
  { id: "Disease Analysis", label: "Disease Analysis" },
];
